### ISSUE TITLE
pod playgrounds command installation incomplete

### ISSUE THREAD

**Issue by clozach** [asmallteapot/cocoapods-playgrounds#10]
When I try, for example, the README's suggestion of `pod playgrounds Alamofire`, I get the following in Terminal (with my own answers added where requested by the CocoaPods team). I haven't seen this with any other CocoaPods command, so I'm checking here first. Will bugger off if it's not your bug. ;)

``` MARKDOWN
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

/usr/local/bin/pod playgrounds Alamofire

### Report

* What did you do?
  * Navigated in Terminal to an empty folder
  * `gem install cocoapods-playgrounds`
  * `pod playgrounds Alamofire`
* What did you expect to happen?
  * Expected a playground to be created with Alamofire embedded
* What happened instead?
  * Got a directory named `AlamofirePlayground` with a `Podfile` and an empty `Alamofire.xcodeproj`

### Stack

   CocoaPods : 0.38.2
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 611c523efb20ce5da94b0db9ef5d31f336a84d69

### Plugins

cocoapods-deintegrate : 0.2.1
cocoapods-playgrounds : 0.0.3
cocoapods-plugins     : 0.4.2
cocoapods-stats       : 0.5.3
cocoapods-trunk       : 0.6.4
cocoapods-try         : 0.4.5

### Error

ArgumentError - wrong number of arguments (2 for 3)
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/executable.rb:50:in `execute_command'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-playgrounds-0.0.3/lib/cocoapods-playgrounds/workspace.rb:15:in `block in generate'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-playgrounds-0.0.3/lib/cocoapods-playgrounds/workspace.rb:13:in `chdir'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-playgrounds-0.0.3/lib/cocoapods-playgrounds/workspace.rb:13:in `generate'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-playgrounds-0.0.3/lib/cocoapods-playgrounds/command/playgrounds.rb:26:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by clozach** [comment]
Doh. Turns out I just needed to update CocoaPods: `sudo gem install cocoapods`
