### ISSUE TITLE
Carthage play failing

### ISSUE THREAD

**Issue by kylebrowning** [asmallteapot/cocoapods-playgrounds#41]
```
carthage-play acquia/waterwheel-swift 
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/executable.rb:69:in `execute_command': [!] /usr/local/bin/carthage update --platform ios (Pod::Informative)

*** Fetching waterwheel-swift
*** Fetching SwiftyJSON
*** Fetching ObjectMapper
*** Fetching SwiftyUserDefaults
*** Fetching Alamofire
*** Checking out Alamofire at "4.0.1"
*** Checking out ObjectMapper at "2.0.0"
*** Downloading SwiftyJSON.framework binary at "3.1.0"
*** Checking out SwiftyUserDefaults at "3.0.0"
*** Checking out waterwheel-swift at "4.3.1"
A shell task (/usr/bin/env git checkout --quiet c0462747a546575665f57fceeb560b5d2830b36b) failed with exit code 128:
fatal: reference is not a tree: c0462747a546575665f57fceeb560b5d2830b36b


    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:40:in `setup_project'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:24:in `block in generate'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:23:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:23:in `generate'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-playgrounds-1.2.2/bin/carthage-play:42:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-playgrounds-1.2.2/bin/carthage-play:46:in `<top (required)>'
    from /usr/local/bin/carthage-play:23:in `load'
    from /usr/local/bin/carthage-play:23:in `<main>'
```

I think it may have to do with the fact that SwiftyJSON is downloading a binary and not checking out?

**Comment by kylebrowning** [comment]
#42 should fix this.
