### ISSUE TITLE
Error with Xcode 9.4 (9F1027a)

### ISSUE THREAD

**Issue by Ozy675** [asmallteapot/cocoapods-playgrounds#62]
I ran `pod playgrounds Alamofire` and I have the same problem as here: https://github.com/asmallteapot/cocoapods-playgrounds/issues/52

It doesn't work with others pods eg: Moya, RxSwift.

I know it was fixed 2 days ago but maybe not for version 9.4?

Anyone else have this problem?

### Error
```
Errno::ENOENT - No such file or directory @ dir_initialize - /Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/File Templates/Source/Playground with Platform Choice.xctemplate
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:43:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:43:in `foreach'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:43:in `dir_for_platform'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:10:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:26:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:26:in `block in generate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:23:in `chdir'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:23:in `generate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/command/playgrounds.rb:46:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.16.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b8a53d010801cce2087b0563d0e39c14058aeedb
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'transport-parents' do

  # Pods for XX
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Alamofire'
  pod 'Moya'
  pod 'SnapKit'
  pod 'PromisesSwift'
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'XXTests' do
    inherit! :search_paths
  end

  target 'XXUITests' do
    inherit! :search_paths
  end

end
```

**Comment by smalldu** [comment]
same issue

**Comment by NicosKaralis** [comment]
Same issue

**Comment by MaciejRz** [comment]
Same issue, Xcode 9.4.1 (9F2000)

**Comment by iT-Boyer** [comment]
xcode10 
```
No such file or directory @ dir_initialize - /Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/File Templates/Source/Playground with Platform Choice.xctemplate
/Library/Ruby/Gems/2.3.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:43:in `open'
....
```

**Comment by alinekborges** [comment]
Same issue here, XCode 10

**Comment by Kirow** [comment]
Had same issue, re-build from git master - works fine.

```
git clone https://github.com/asmallteapot/cocoapods-playgrounds.git
gem build cocoapods-playgrounds.gemspec
sudo gem install cocoapods-playgrounds-1.2.2.gem
```

Then `pod playgrounds PodName` - it will open project in xCode, then you should manually build **Pods-EmptyPlayground** for simulator (prefer this to be automated) and you are ready to go.

**Comment by HellotalkXJP** [comment]
Same issue here, Xcode 10
how to resovle it
