### ISSUE TITLE
current verison doesn't work with Xcode 10

### ISSUE THREAD

**Issue by HellotalkXJP** [asmallteapot/cocoapods-playgrounds#64]
### Error

```
Errno::ENOENT - No such file or directory @ dir_initialize - /Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/File Templates/Source/Playground with Platform Choice.xctemplate
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:43:in `open'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:43:in `foreach'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:43:in `dir_for_platform'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/generate.rb:10:in `initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:26:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:26:in `block in generate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:23:in `chdir'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/workspace.rb:23:in `generate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-playgrounds-1.2.2/lib/cocoapods-playgrounds/command/playgrounds.rb:46:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by MihaelIsaev** [comment]
Yeah, it always shows error like this

    error: Build input file cannot be found:
    /Users/mihael/Library/Developer/Xcode/DerivedData/
    SnapKit-gymzmybttjblarbenmbshzbmhwoc/Build/
    Products/Debug-iphoneos/SnapKitPlayground.app/SnapKitPlayground
